# Generated by Django 5.2.4 on 2025-07-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/profile/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(editable=False, unique=True)),
            ],
        ),
    ]
