# Generated by Django 5.2.4 on 2025-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_profilephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephoto',
            name='show_in_slideshow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='slideshow_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
