# Generated by Django 5.2.4 on 2025-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profilephoto_show_in_slideshow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='description',
            field=models.TextField(default='This site was created by me, using Django3 framework'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(default='Maxim Rezan | Engineering student', max_length=200),
        ),
    ]
