# Generated by Django 5.2.4 on 2025-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_cv_description_alter_cv_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Maxim Rezan | Engineering student', max_length=200)),
                ('description', models.TextField(default='This site was created by me, using Django3 framework')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cv',
            name='description',
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(default='My CV', max_length=100),
        ),
    ]
